# Misc
beatrun.misc.yes=Tak
beatrun.misc.no=Nie
beatrun.misc.ok=OK
beatrun.misc.cancel=Anuluj
beatrun.misc.add=Dodaj
beatrun.misc.delete=Usuń
beatrun.misc.save=Zapisz
beatrun.misc.noclipdetected=Wykryto Noclip! Odródź się, aby zresetować bieg
beatrun.misc.checkconsole=Sprawdź konsolę!

# Addon Warning
beatrun.addonwarning.warntext=UWAGA\nWyłącz następujące dodatki przed rozpoczęciem gry\nlub przesłaniem jakichkolwiek zgłoszeń na GitHuba:
beatrun.addonwarning.quitbutton=Wyjdź do menu głównego
beatrun.addonwarning.play=Graj
beatrun.addonwarning.conflictfound=ZNALEZIONO DODATKI POWODUJĄCE KONFLIKTY

# Build Mode HUD
beatrun.buildmodehud.info=Indeks: %s\nWybrane: %s\nKąt: %s
beatrun.buildmodehud.props=Menu / Przedmioty
beatrun.buildmodehud.entities=Menu / Istoty
beatrun.buildmodehud.drag=Przeciągnij (G)
beatrun.buildmodehud.copy=Kopiuj (SHIFT+D)
beatrun.buildmodehud.delete=Usuń (DEL/BCKSPC)
beatrun.buildmodehud.highlight=Zaznacz (T)
beatrun.buildmodehud.select=Wybierz
beatrun.buildmodehud.zipline=Tyrolka (SHIFT = Dwukierunkowa)

# ConVars
beatrun.convars.hudxp=Pokaż całkowitą liczbę PD obok nicku
beatrun.convars.hudsway=Kołysanie interfejsu
beatrun.convars.huddynamic=Ukryj interfejs podczas poruszania się
beatrun.convars.hudhidden=Ukryj większość interfejsu
beatrun.convars.hudreticle=Wyświetl kropkę
beatrun.convars.hudtextcolor=Kolor tekstu interfejsu\nDomyślnie: 255 255 255 255
beatrun.convars.hudcornercolor=Kolor interfejsu w rogu ekranu\nDomyślnie: 20 20 20 100
beatrun.convars.hudfloatxpcolor=Kolor "unoszących się" punktów PD na interfejsie\nDomyślnie: 255 255 255 255
beatrun.convars.nametags=Wyświetl identyfikatory nad graczami
beatrun.convars.apikey=Klucz API
beatrun.convars.domain=Domena bazy danych biegów
beatrun.convars.theme=Zmień motyw menu tras. Dostępne są tryby "Ciemny" i "Jasny".
beatrun.convars.viewbob=Intensywność kołysania kamery
beatrun.convars.viewbobstabilization=Włącz, aby zmniejszyć chorobę lokomocyjną za pomocą utrzymywania stabilności kamery w ruchu
beatrun.convars.fov=Zmień pole widzenia gracza
beatrun.convars.cpsave=Odrodzenie podczas biegu spowoduje powrót do ostatniego zaliczonego punktu kontrolnego
beatrun.convars.faststart=Szybsze odliczanie do startu
beatrun.convars.disablegrapple=Wyłącz zdolność używania tyrolki
beatrun.convars.puristmode=Tryb purystyczny to opcja po stronie klienta, która poważnie ogranicza zdolność do poruszania się na boki w powietrzu, tak jak w grach z serii ME.\n0 = Brak ograniczeń\n1 = Zmniejszona prędkość ruchu w powietrzu.
beatrun.convars.quickturnground=Umożliwia szybki obrót za pomocą ataku drugorzędnego na ziemi
beatrun.convars.quickturnhandsonly=Umożliwia szybki obrót tylko w trybie "Rąk biegacza"
beatrun.convars.showspeedometer=Włącz/Wyłącz widoczność prędkościomierza
beatrun.convars.speedometermode=Zmień tryb prędkościomierza

# HUD
beatrun.hud.course=Trasa: %s
beatrun.hud.freeplay=Rozgrywka swobodna
beatrun.hud.lvl=Poziom: %s
beatrun.hud.infector=Infekujący

# Courses Menu
beatrun.coursesmenu.save=Zapisz
beatrun.coursesmenu.start=Rozpocznij
beatrun.coursesmenu.upload=Prześlij
beatrun.coursesmenu.upload.confirm=Czy na pewno chcesz przesłać tą trasę do bazy danych?
beatrun.coursesmenu.delete=Usuń
beatrun.coursesmenu.delete.confirm=Czy na pewno chcesz usunąć tą trasę?
beatrun.coursesmenu.downloads=Pobrań: %d
beatrun.coursesmenu.uploadedat=Przesłano: %s
beatrun.coursesmenu.copied=Skopiowano do schowka

beatrun.coursesmenu.localpage=Lokalne
beatrun.coursesmenu.localpage.savecourse=Zapisz trasę
beatrun.coursesmenu.localpage.buildmode=Włącz/Wyłącz tryb budowania
beatrun.coursesmenu.localpage.freeplay=Wróć do rozgrywki swobodnej
beatrun.coursesmenu.localpage.savedcourses=Zapisano trasę dla %s
beatrun.coursesmenu.localpage.nosavedcourses=Nie znaleziono zapisanych tras...

beatrun.coursesmenu.onlinepage=Sieciowe
beatrun.coursesmenu.onlinepage.currentmap=Tylko obecna mapa
beatrun.coursesmenu.onlinepage.notcurrentmap=Wszystkie trasy
beatrun.coursesmenu.onlinepage.search.placeholder=Wyszukaj trasy...
beatrun.coursesmenu.onlinepage.start=Rozpocznij trasę
beatrun.coursesmenu.onlinepage.start.message=Nie subskrybujesz tej mapy. Jeśli rozpoczniesz trasę, możesz utknąć. Czy chcesz ją zasubskrybować?
beatrun.coursesmenu.onlinepage.openworkshop=Otwórz warsztat
beatrun.coursesmenu.onlinepage.iknowwhatimdoing=Wiem co robię
beatrun.coursesmenu.onlinepage.download=Pobierz
beatrun.coursesmenu.onlinepage.overwrite=Nadpisać?
beatrun.coursesmenu.onlinepage.overwrite.confirm=Plik tej trasy już istnieje. Czy chcesz go zastąpić?

beatrun.coursesmenu.profilepage=Profil
beatrun.coursesmenu.profilepage.register=Otwórz stronę rejestracji w nakładce Steam
beatrun.coursesmenu.profilepage.copylink=Skopiuj link do rejestracji
beatrun.coursesmenu.profilepage.message=Aby przesłać trasy, potrzebujesz klucza API\nPoniższy przycisk otworzy stronę internetową w nakładce Steam, na której możesz się zarejestrować\nWykorzystamy wyłącznie Twój identyfikator SteamID i nazwę użytkownika!\nNie zbieramy żadnych innych danych!\nJeśli wyłączyłeś nakładkę lub nie działa ona poprawnie, skopiuj adres i otwórz go w zewnętrznej przeglądarce internetowej.
beatrun.coursesmenu.profilepage.key=Klucz API: %s
beatrun.coursesmenu.profilepage.changekey=Zmień klucz API
beatrun.coursesmenu.profilepage.changekey.placeholder=Wprowadź nowy klucz API...
beatrun.coursesmenu.profilepage.stats=Przesłane trasy: %d | Wszystkich pobrań: %d
beatrun.coursesmenu.profilepage.nouploadedcourses=Nie przesłałeś jeszcze żadnych tras...

beatrun.coursesmenu.settings=Ustawienia
beatrun.coursesmenu.settings.domain=Domena bazy danych tras
beatrun.coursesmenu.settings.theme=Motyw

beatrun.coursesmenu.themes.dark=Ciemny
beatrun.coursesmenu.themes.light=Jasny

beatrun.coursesmenu.save.placeholder=Wprowadź nazwę trasy...
beatrun.coursesmenu.save.maxspeedlock=Ogranicz maksymalną prędkość

# Courses Menu Notifications
beatrun.coursesmenu.notification.openconsole=Błąd, sprawdź konsolę

beatrun.coursesmenu.notification.fetch.failed=Nie udało się pobrać danych z serwera/wysłać ich na serwer. Sprawdź konsolę.
beatrun.coursesmenu.notification.upload.success=Przesłanie zakończyło się powodzeniem, sprawdź konsolę

beatrun.coursesmenu.notification.save.failed=Nie udało się zapisać trasy do pliku
beatrun.coursesmenu.notification.save.success=Zapisano trasę w data/%s

beatrun.coursesmenu.notification.read.failed=Nie udało się odczytać/otworzyć pliku

beatrun.coursesmenu.notification.startingcourse=Rozpoczęto trasę %s...

beatrun.coursesmenu.notification.nokey=Brak klucza API

# Tools Menu
beatrun.toolsmenu.client=Klient
beatrun.toolsmenu.server=Serwer
beatrun.toolsmenu.extra=Ekstra

# Tools Menu Courses Section
beatrun.toolsmenu.courses.name=Trasy
beatrun.toolsmenu.courses.desc=Ustawienia tras

beatrun.toolsmenu.courses.raceyourghost=Wyścig z duchem
beatrun.toolsmenu.courses.raceyourghostdesc=Ścigaj się z duchem odtwarzającym ruchy,\nktóre wykonałeś podczas swojej najlepszej próby

beatrun.toolsmenu.courses.faststart=Szybki start
beatrun.toolsmenu.courses.faststartdesc=Szybsze odliczanie na początku trasy

beatrun.toolsmenu.courses.checkpointsave=Zapis w punkcie kontrolnym
beatrun.toolsmenu.courses.checkpointsavedesc=Odrodzenie w ostatnim zaliczonym punkcie kontrolnym na trasie

# Tools Menu HUD Section
beatrun.toolsmenu.hud.name=Interfejs
beatrun.toolsmenu.hud.desc=Ustawienia interfejsu

beatrun.toolsmenu.hud.dynamic=Dynamiczny interfejs
beatrun.toolsmenu.hud.dynamicdesc=Ukrywa interfejs w ruchu

beatrun.toolsmenu.hud.sway=Kołysanie interfejsu
beatrun.toolsmenu.hud.swaydesc=Włącz/Wyłącz kołysanie interfejsu

beatrun.toolsmenu.hud.nametags=Pokaż identyfikatory
beatrun.toolsmenu.hud.nametagsdesc=Włącz/Wyłącz wyświetlanie identyfikatorów nad graczami

beatrun.toolsmenu.hud.hudxp=Wyświetl PD na interfejsie
beatrun.toolsmenu.hud.hudxpdesc=Pokaż całkowitą liczbę PD w pobliżu swojego nicku

beatrun.toolsmenu.hud.showspeedometer=Pokaż prędkościomierz
beatrun.toolsmenu.hud.showspeedometerdesc=Pokazuje prędkościomierz na interfejsie

beatrun.toolsmenu.hud.speedometermode=Tryb prędkościomierza
beatrun.toolsmenu.hud.speedometermode1=km/h
beatrun.toolsmenu.hud.speedometermode2=mph
beatrun.toolsmenu.hud.speedometermode3=hu/h

beatrun.toolsmenu.hud.showSpeedometer=Pokaż prędkościomierz
beatrun.toolsmenu.hud.showSpeedometerDesc=Pokazuje prędkościomierz na interfejsie (ukrycie interfejsu nie wpływa na to ustawienie)

beatrun.toolsmenu.hud.keystrokes=Pokaż naciśnięte klawisze
beatrun.toolsmenu.hud.keystrokesdesc=Pokazuje na interfejsie klawisze, które wciskasz podczas gry

beatrun.toolsmenu.hud.keystrokes_x_offset=Położenie naciśniętych klawiszy w osi X
beatrun.toolsmenu.hud.keystrokes_y_offset=Położenie naciśniętych klawiszy w osi Y

beatrun.toolsmenu.hud.keystrokes_corner=Wyrównanie naciśniętych klawiszy do rogu
beatrun.toolsmenu.hud.keystrokes_corner1=Góra-lewo
beatrun.toolsmenu.hud.keystrokes_corner2=Góra-prawo
beatrun.toolsmenu.hud.keystrokes_corner3=Dół-lewo
beatrun.toolsmenu.hud.keystrokes_corner4=Dół-prawo

beatrun.toolsmenu.hud.hidden=Widoczność interfejsu
beatrun.toolsmenu.hud.hidden0=Pokaż
beatrun.toolsmenu.hud.hidden1=Pokaż tylko tryb gry i prędkość
beatrun.toolsmenu.hud.hidden2=Ukryj

beatrun.toolsmenu.hud.textcolor=Kolor tekstu interfejsu
beatrun.toolsmenu.hud.cornercolor=Kolor rogu interfejsu
beatrun.toolsmenu.hud.floatxpcolor=Kolor "unoszących się" punktów PD na interfejsie

# Tools Menu Camera Section
beatrun.toolsmenu.camera.name=Kamera
beatrun.toolsmenu.camera.desc=Ustawienia kamery

beatrun.toolsmenu.camera.colormodifyfilter=Wyłącz filtr kolorów
beatrun.toolsmenu.camera.colormodifyfilterdesc=Wyłącza filtr modyfikujący kolory
beatrun.toolsmenu.camera.stabilization=Stabilizacja kołysania kamery w ruchu
beatrun.toolsmenu.camera.stabilizationdesc=Włącz, aby zmniejszyć efekt powodujący chorobę lokomocyjną za pomocą utrzymywania stabilności kamery w ruchu
beatrun.toolsmenu.camera.intensity=Intensywność kołysania kamery w ruchu
beatrun.toolsmenu.camera.fov=Pole widzenia
beatrun.toolsmenu.camera.fovdesc=Zmienia pole widzenia

# Tools Menu Gameplay Section
beatrun.toolsmenu.gameplay.name=Rozgrywka
beatrun.toolsmenu.gameplay.desc=Ustawienia rozgrywki

beatrun.toolsmenu.gameplay.animset=Zestaw animacji
beatrun.toolsmenu.gameplay.animset1=Nowe (stworzone przez MTB)
beatrun.toolsmenu.gameplay.animset2=Oryginalne (stworzone przez datae, naprawione przez MTB)

beatrun.toolsmenu.gameplay.catalystcoil=Animacja skoku z podwiniętymi nogami z Catalyst
beatrun.toolsmenu.gameplay.catalystcoildesc=Ta animacja zostanie użyta tylko z wybranymi "Rękami biegacza", w innym wypadku zostanie użyta normalna animacja

beatrun.toolsmenu.gameplay.quickturnground=Szybki obrót na ziemi
beatrun.toolsmenu.gameplay.quickturngrounddesc=Umożliwia szybki obrót za pomocą ataku drugorzędnego na ziemi

beatrun.toolsmenu.gameplay.quickturnhandsonly=Szybki obrót tylko z rękami
beatrun.toolsmenu.gameplay.quickturnhandsonlydesc=Umożliwia szybki obrót tylko w trybie "Rąk biegacza"

beatrun.toolsmenu.gameplay.autohandswitch=Automatyczna zmiana rąk
beatrun.toolsmenu.gameplay.autohandswitchdesc=Automatycznie zmiania broń na "Ręce biegacza" przy wykonywaniu specyficznych ruchów.

beatrun.toolsmenu.gameplay.puristmode=Tryb Purysty
beatrun.toolsmenu.gameplay.puristmodedesc=Tryb purystyczny to opcja po stronie klienta, która poważnie ogranicza zdolność do strafe'owania w powietrzu, tak jak w grach z serii ME.\nWył. = Brak ograniczeń\nWł. = Zmniejszona prędkość ruchu w powietrzu.

beatrun.toolsmenu.gameplay.disablegrapple=Wyłącz zdolność używania tyrolki
beatrun.toolsmenu.gameplay.disablegrappledesc=Wyłącza zdolność używania tyrolki

beatrun.toolsmenu.gameplay.rollspeedloss=Utrata prędkości przy przewrocie
beatrun.toolsmenu.gameplay.rollspeedlossdesc=Włącz/Wyłącz utratę prędkości przy przewrocie na końcu upadku

beatrun.toolsmenu.gameplay.wind=Efekt wiatru
beatrun.toolsmenu.gameplay.winddesc=Włącza dźwięki wiatru w trakcie biegu

# Tools Menu Misc Section
beatrun.toolsmenu.misc.name=Inne
beatrun.toolsmenu.misc.desc=Inne ustawienia

beatrun.toolsmenu.misc.propspawn=Przywoływanie przedmiotów
beatrun.toolsmenu.misc.propspawndesc=Umożliwia graczom bez praw administratora przywoływanie przedmiotów i postaci.

beatrun.toolsmenu.misc.weaponspawn=Przywoływanie broni
beatrun.toolsmenu.misc.weaponspawndesc=Umożliwia graczom bez praw administratora przywoływanie broni.

beatrun.toolsmenu.misc.overdrivemp=Dopalenie w trybie wieloosobowym
beatrun.toolsmenu.misc.overdrivempdesc=Umożliwia korzystanie z dopalenia na serwerze.

beatrun.toolsmenu.misc.healthregen=Regeneracja zdrowia
beatrun.toolsmenu.misc.healthregendesc=Włącz/Wyłącz regenerację zdrowia

beatrun.toolsmenu.misc.lerealisticclimbing=Realistyczna wspinaczka
beatrun.toolsmenu.misc.lerealisticclimbingdesc=Nie pozwala na bieganie po ścianach ani wspinaczkę, jeśli nie masz na sobie rąk przystosowanych do biegania.

beatrun.toolsmenu.misc.ledgegrabdamage=Obrażenia od złapania za krawędź po upadku
beatrun.toolsmenu.misc.ledgegrabdamagedesc=Włącza/wyłącza obrażenia za złapanie się krawędzi po upadku z dużej lub śmiertelnej wysokości

# Tools Menu Moves Section
beatrun.toolsmenu.moves.name=Ruchy
beatrun.toolsmenu.moves.desc=Ustawienia ruchów
beatrun.toolsmenu.moves.help=Możesz nurkować, używając Ctrl + PPM w powietrzu! \nE + LPM włącza/wyłącza dopalanie.

beatrun.toolsmenu.moves.speedlimit=Limit prędkości
beatrun.toolsmenu.moves.speedlimitdesc=Zmienia limit prędkości gracza\nDomyślnie: 325

beatrun.toolsmenu.moves.forcepuristmode=Wymuś Tryb Purysty
beatrun.toolsmenu.moves.forcepuristmodedesc=Wymusza tryb purystyczny na wszystkich graczach na serwerze.

beatrun.toolsmenu.moves.realisticwallrunning="Realistyczne" bieganie po ścianach
beatrun.toolsmenu.moves.realisticwallrunningdesc=Nie tracisz prędkości w trakcie rozpoczęcia biegu po ścianie, gdy ta opcja jest wyłączona.

beatrun.toolsmenu.moves.kickglitch=Wersja "Kick Glitch'a"
beatrun.toolsmenu.moves.kickglitch0=Wyłączony
beatrun.toolsmenu.moves.kickglitch1=Oryginalna (mnożnik prędkości)
beatrun.toolsmenu.moves.kickglitch2=W stylu Mirror's Edge'a (niewidzialna platforma)

beatrun.toolsmenu.moves.quakejump=Skok w stylu Quake'a
beatrun.toolsmenu.moves.quakejumpdesc=Włącz/Wyłącz mechanikę skakania podobną do tej z gry Quake\nNaciśnij skok po kroku w bok

beatrun.toolsmenu.moves.sidestep=Krok w bok
beatrun.toolsmenu.moves.sidestepdesc=Włącz/Wyłącz krok w bok\nA/D + PPM

beatrun.toolsmenu.moves.disarm=Rozbrojenie
beatrun.toolsmenu.moves.disarmdesc=Włącz/Wyłącz możliwość rozbrajania NPC\nNaciśnij UŻYJ na NPC

beatrun.toolsmenu.moves.divesettings=Ustawienia nurkowania

beatrun.toolsmenu.moves.totsugeki=Totsugeki
beatrun.toolsmenu.moves.totsugekidesc=Włącz/Wyłącz ruch Totsugeki'ego\nZanurkuj zaraz po skoku w stylu Quake'a

beatrun.toolsmenu.moves.totsugekispam=Spamowanie ruchu Totsugeki'ego
beatrun.toolsmenu.moves.totsugekispamdesc=Włącz/Wyłącz możliwość spamowania ruchu Totsugeki'ego

beatrun.toolsmenu.moves.totsugekiheading=Poruszanie w ruchu Totsugeki'ego
beatrun.toolsmenu.moves.totsugekiheadingdesc=Umożliwia używanie ruchu Totsugeki'ego w osi X (góra/dół)

beatrun.toolsmenu.moves.totsugekidirection=Kierunek ruchu Totsugeki'ego
beatrun.toolsmenu.moves.totsugekidirectiondesc=Umożliwia wykonanie ruchu Totsugeki'ego w innym kierunku\nW połączeniu z opcją "Spamowania" oraz "Poruszania", sprawi, że odlecisz =)

beatrun.toolsmenu.moves.totsugekiaudio=Głos Totsugeki'ego
beatrun.toolsmenu.moves.totsugekiaudiodesc=Włącz/Wyłącz głos Totsugeki'ego

# Tools Menu Gamemodes Section
beatrun.toolsmenu.gamemodes.name=Tryby gry
beatrun.toolsmenu.gamemodes.desc=Ustawienia trybów gry
beatrun.toolsmenu.gamemodes.error=Jesteś w trakcie rozgrywki w innym trybie gry!

beatrun.toolsmenu.gamemodes.infection=Włącz/Wyłącz tryb gry "Infekcja"
beatrun.toolsmenu.gamemodes.infectionstarttime=Czas przed rozpoczęciem rozgrywki
beatrun.toolsmenu.gamemodes.infectiongametime=Długość rozgrywki
beatrun.toolsmenu.gamemodes.infectiontime=Czas w sekundach
beatrun.toolsmenu.gamemodes.datatheft=Włącz/Wyłącz tryb gry "Kradzież danych"
beatrun.toolsmenu.gamemodes.deathmatch=Włącz/Wyłącz tryb gry "Pojedynek"
beatrun.toolsmenu.gamemodes.eventmode=Włącz/Wyłącz tryb gry "Impreza"
beatrun.toolsmenu.gamemodes.loadoutseditor=Edytor wyposażenia
beatrun.toolsmenu.gamemodes.blacklisteditor=Edytor czarnej listy

# Tools Menu Extra Section
beatrun.toolsmenu.extra.name=Dodatkowe
beatrun.toolsmenu.extra.desc=Dodatkowe ustawienia dla naczaśników/spoceńców

beatrun.toolsmenu.extra.stats=Dodatkowe statystyki
beatrun.toolsmenu.extra.statsdesc=Wyświetla dodatkowe statystyki oprócz prędkościomierza, aby zapewnić więcej informacji pomocnych przy trudniejszych trikach

beatrun.toolsmenu.extra.speedrunsverif=Statystyki weryfikacji naczasu
beatrun.toolsmenu.extra.speedrunsverifdesc=Pokazuje informacje o twoich ustawieniach (Tryb Purysty, "Realistyczne" bieganie po ścianach oraz wersja Kick Glitch'a)

# Loadouts and Blacklist Editor
beatrun.loadoutseditor.title=Edytor wyposażenia
beatrun.loadoutseditor.loadout=Wyposażenie %s
beatrun.loadoutseditor.addweapon=Dodaj broń

beatrun.blacklisteditor.title=Czarna lista (dla losowych wyposażeń)
beatrun.blacklisteditor.blacklisted=Zablokowane
beatrun.blacklisteditor.allowed=Dozwolone

# Checkpoints
beatrun.checkpoints.countdown1=Gotowy
beatrun.checkpoints.countdown2=Do startu
beatrun.checkpoints.countdown3=START!

# DataTheft
beatrun.datatheft.name=Kradzież danych (%s)
beatrun.datatheft.start=Kradzież danych! Zabijaj innych graczy, aby zbierać dane, które następnie zdeponuj w banku.

# Deathmatch
beatrun.deathmatch.name=Pojedynek
beatrun.deathmatch.start=Pojedynek! Zabijaj innych graczy, aby zdobywać punkty!

# Eventmode
beatrun.eventmode.name=[TRYB IMPREZY]
beatrun.eventmode.start=Rozpoczęła się impreza! Postępuj zgodnie z instrukcjami administracji.
beatrun.eventmode.memberlabel=Członek
beatrun.eventmode.memberhud=Bierzesz udział!
beatrun.eventmode.suspendedlabel=Zawieszony
beatrun.eventmode.suspendedhud=Zostałeś zawieszony!
beatrun.eventmode.managerlabel=Menadżer
beatrun.eventmode.managerhud=[MENADŻER]

# Infection
beatrun.infection.name=Infekcja
beatrun.infection.infectedtext=(Zainfekowany)
beatrun.infection.humantext=(Człowiek)
beatrun.infection.start=Infekcja! Dotykaj innych graczy, aby ich zainfekować\n%s gracz(y) zostanie zainfekowany(ch) %ss
beatrun.infection.nosurvivors=Nikt nie przeżył...
beatrun.infection.infected=został zainfekowany!
beatrun.infection.infectedby=zainfekował
beatrun.infection.award=Nagrodzono cię 200-ma PD za przetrwanie!
beatrun.infection.awardinfected=Nagrodzono cię 100-ma PD za odrodzenie się jako zainfekowany!
beatrun.infection.end=Rozgrywka zakończkona!\nPrzetrwańcy: %s\nReset za 15s

# Server ConVars
beatrun.randomloadoutsdesc=Zmienia losowe uzbrojenie w trybach "Pojedynek" i "Kradzież danych"
beatrun.randombeatrunloadouts=Uzbrojenie Beatrun
beatrun.randommwloadouts=Uzbrojenie MW Base
beatrun.randomarc9loadouts=Uzbrojenie ARC9
beatrun.randomarccwloadouts=Uzbrojenie ARCCW
beatrun.randomtfaloadouts=Uzbrojenie TFA
