# Misc
beatrun.misc.yes=是
beatrun.misc.no=否
beatrun.misc.ok=确定
beatrun.misc.cancel=取消
beatrun.misc.add=添加
beatrun.misc.delete=删除
beatrun.misc.save=保存
beatrun.misc.noclipdetected=检测到 Noclip！按 R 重生以重新开始路线
beatrun.misc.checkconsole=查看控制台！

# Addon Warning
beatrun.addonwarning.warntext=注意\n请在游玩前禁用以下插件\n或在向 GitHub 提交任何问题前禁用它们：
beatrun.addonwarning.quitbutton=返回主菜单
beatrun.addonwarning.play=开始游戏
beatrun.addonwarning.conflictfound=检测到冲突的插件

# Build Mode HUD
beatrun.buildmodehud.info=索引：%s\n已选：%s\n角度：%s
beatrun.buildmodehud.props=菜单 / 道具
beatrun.buildmodehud.entities=菜单 / 实体
beatrun.buildmodehud.drag=拖动 (G)
beatrun.buildmodehud.copy=复制 (SHIFT+D)
beatrun.buildmodehud.delete=删除 (DEL/BCKSPC)
beatrun.buildmodehud.highlight=高亮 (T)
beatrun.buildmodehud.select=选择
beatrun.buildmodehud.zipline=滑索 (SHIFT = 双向)

# ConVars
beatrun.convars.hudxp=在昵称旁显示总 XP
beatrun.convars.hudsway=显示 HUD 摆动
beatrun.convars.huddynamic=移动时隐藏 HUD
beatrun.convars.hudhidden=隐藏大部分 HUD
beatrun.convars.hudreticle=显示准星
beatrun.convars.hudtextcolor=HUD 文字颜色\n默认：255 255 255 255
beatrun.convars.hudcornercolor=HUD 边角颜色\n默认：20 20 20 100
beatrun.convars.hudfloatxpcolor=HUD 浮动 XP 颜色\n默认：255 255 255 255
beatrun.convars.nametags=在玩家头顶显示姓名标签
beatrun.convars.apikey=API 密钥
beatrun.convars.domain=路线数据库域名
beatrun.convars.theme=更改路线菜单主题。可用值："Dark" 与 "Light"。
beatrun.convars.viewbob=视角起伏强度
beatrun.convars.viewbobstabilization=开启后可通过让视角起伏保持玩家视线位置居中来减轻晕动症
beatrun.convars.fov=更改玩家视野（FOV）
beatrun.convars.cpsave=在路线中重生会回到上一个触发的检查点
beatrun.convars.faststart=更快的开始倒计时
beatrun.convars.disablegrapple=切换抓钩能力
beatrun.convars.puristmode=纯粹模式是一个客户端偏好设置，会大幅削弱空中横移（Strafe）的能力，这与《镜之边缘》系列的处理方式一致。\n0 = 无限制\n1 = 空中移动速度降低
beatrun.convars.quickturnground=切换：在地面时用副攻击快速转身
beatrun.convars.quickturnhandsonly=切换：仅在使用 "Runner Hands" 时快速转身
beatrun.convars.showspeedometer=切换速度表可见性
beatrun.convars.speedometermode=更改速度表模式

# HUD
beatrun.hud.course=路线：%s
beatrun.hud.freeplay=自由模式
beatrun.hud.lvl=等级：%s
beatrun.hud.infector=感染者

# Courses Menu
beatrun.coursesmenu.save=保存
beatrun.coursesmenu.start=开始
beatrun.coursesmenu.upload=上传
beatrun.coursesmenu.upload.confirm=确定要将该路线上传到数据库吗？
beatrun.coursesmenu.delete=删除
beatrun.coursesmenu.delete.confirm=确定要删除这条路线吗？
beatrun.coursesmenu.downloads=下载次数：%d
beatrun.coursesmenu.uploadedat=上传时间：%s
beatrun.coursesmenu.copied=已复制到剪贴板

beatrun.coursesmenu.localpage=本地
beatrun.coursesmenu.localpage.savecourse=保存路线
beatrun.coursesmenu.localpage.buildmode=切换建造模式
beatrun.coursesmenu.localpage.freeplay=返回自由模式
beatrun.coursesmenu.localpage.savedcourses=%s 的已保存路线
beatrun.coursesmenu.localpage.nosavedcourses=未找到已保存路线...

beatrun.coursesmenu.onlinepage=在线
beatrun.coursesmenu.onlinepage.currentmap=仅当前地图
beatrun.coursesmenu.onlinepage.notcurrentmap=全部路线
beatrun.coursesmenu.onlinepage.search.placeholder=搜索路线...
beatrun.coursesmenu.onlinepage.start=开始路线
beatrun.coursesmenu.onlinepage.start.message=你未订阅该地图。若开始路线，你可能会被卡住。要订阅吗？
beatrun.coursesmenu.onlinepage.openworkshop=打开创意工坊
beatrun.coursesmenu.onlinepage.iknowwhatimdoing=我知道我在做什么
beatrun.coursesmenu.onlinepage.download=下载
beatrun.coursesmenu.onlinepage.overwrite=要覆盖吗？
beatrun.coursesmenu.onlinepage.overwrite.confirm=该路线文件已存在。要覆盖吗？

beatrun.coursesmenu.profilepage=个人资料
beatrun.coursesmenu.profilepage.register=在 Steam 覆盖层中打开注册页面
beatrun.coursesmenu.profilepage.copylink=复制注册链接
beatrun.coursesmenu.profilepage.message=上传路线需要 API 密钥\n下面的按钮会在 Steam 覆盖层中打开注册网页，\n我们只会使用你的 SteamID 和用户名！\n我们不会收集任何其他信息！\n如果你没有覆盖层或无法使用，请复制该地址并在浏览器中打开。
beatrun.coursesmenu.profilepage.key=API 密钥：%s
beatrun.coursesmenu.profilepage.changekey=更换 API 密钥
beatrun.coursesmenu.profilepage.changekey.placeholder=输入新的 API 密钥...
beatrun.coursesmenu.profilepage.stats=你的上传：%d | 总下载：%d
beatrun.coursesmenu.profilepage.nouploadedcourses=你还没有上传任何路线...

beatrun.coursesmenu.settings=设置
beatrun.coursesmenu.settings.domain=路线数据库域名
beatrun.coursesmenu.settings.theme=主题

beatrun.coursesmenu.themes.dark=深色
beatrun.coursesmenu.themes.light=浅色

beatrun.coursesmenu.save.placeholder=输入路线名称...
beatrun.coursesmenu.save.maxspeedlock=限制最高速度

# Courses Menu Notifications
beatrun.coursesmenu.notification.openconsole=错误，请查看控制台

beatrun.coursesmenu.notification.fetch.failed=与服务器收发数据失败，请查看控制台
beatrun.coursesmenu.notification.upload.success=上传成功，请查看控制台

beatrun.coursesmenu.notification.save.failed=保存路线到文件失败
beatrun.coursesmenu.notification.save.success=已将路线保存到 data/%s

beatrun.coursesmenu.notification.read.failed=读取/打开文件失败

beatrun.coursesmenu.notification.startingcourse=正在开始路线 %s...

beatrun.coursesmenu.notification.nokey=未设置 API 密钥

# Tools Menu
beatrun.toolsmenu.client=客户端
beatrun.toolsmenu.server=服务器
beatrun.toolsmenu.extra=额外

# Tools Menu Courses Section
beatrun.toolsmenu.courses.name=路线
beatrun.toolsmenu.courses.desc=路线设置

beatrun.toolsmenu.courses.raceyourghost=与幽灵竞速
beatrun.toolsmenu.courses.raceyourghostdesc=与重现你最佳路线成绩的幽灵竞速

beatrun.toolsmenu.courses.faststart=快速开始
beatrun.toolsmenu.courses.faststartdesc=路线开始时更快的倒计时

beatrun.toolsmenu.courses.checkpointsave=检查点保存
beatrun.toolsmenu.courses.checkpointsavedesc=在路线中重生将回到上一个触发的检查点

# Tools Menu HUD Section
beatrun.toolsmenu.hud.name=HUD
beatrun.toolsmenu.hud.desc=HUD 设置

beatrun.toolsmenu.hud.dynamic=动态 HUD
beatrun.toolsmenu.hud.dynamicdesc=移动时隐藏 HUD

beatrun.toolsmenu.hud.sway=HUD 摆动
beatrun.toolsmenu.hud.swaydesc=切换 HUD 摆动

beatrun.toolsmenu.hud.nametags=显示姓名标签
beatrun.toolsmenu.hud.nametagsdesc=切换玩家头顶姓名标签

beatrun.toolsmenu.hud.hudxp=显示 HUD XP
beatrun.toolsmenu.hud.hudxpdesc=在昵称旁显示总 XP

beatrun.toolsmenu.hud.showspeedometer=显示速度表
beatrun.toolsmenu.hud.showspeedometerdesc=在 HUD 上显示速度表

beatrun.toolsmenu.hud.speedometermode=速度表模式
beatrun.toolsmenu.hud.speedometermode1=km/h
beatrun.toolsmenu.hud.speedometermode2=mph
beatrun.toolsmenu.hud.speedometermode3=hu/h

beatrun.toolsmenu.hud.showSpeedometer=显示速度表
beatrun.toolsmenu.hud.showSpeedometerDesc=在 HUD 上显示速度表（隐藏 HUD 不影响其可见性）

beatrun.toolsmenu.hud.keystrokes=显示按键
beatrun.toolsmenu.hud.keystrokesdesc=显示你按下的按键

beatrun.toolsmenu.hud.keystrokes_x_offset=按键 X 偏移
beatrun.toolsmenu.hud.keystrokes_y_offset=按键 Y 偏移

beatrun.toolsmenu.hud.keystrokes_corner=按键对齐方式
beatrun.toolsmenu.hud.keystrokes_corner1=左上
beatrun.toolsmenu.hud.keystrokes_corner2=右上
beatrun.toolsmenu.hud.keystrokes_corner3=左下
beatrun.toolsmenu.hud.keystrokes_corner4=右下

beatrun.toolsmenu.hud.hidden=HUD 可见性
beatrun.toolsmenu.hud.hidden0=显示
beatrun.toolsmenu.hud.hidden1=仅游戏模式与速度
beatrun.toolsmenu.hud.hidden2=隐藏

beatrun.toolsmenu.hud.textcolor=HUD 文字颜色
beatrun.toolsmenu.hud.cornercolor=HUD 边角颜色
beatrun.toolsmenu.hud.floatxpcolor=HUD 浮动 XP 颜色

# Tools Menu Camera Section
beatrun.toolsmenu.camera.name=相机
beatrun.toolsmenu.camera.desc=相机设置

beatrun.toolsmenu.camera.colormodifyfilter=禁用颜色滤镜
beatrun.toolsmenu.camera.colormodifyfilterdesc=禁用颜色滤镜
beatrun.toolsmenu.camera.stabilization=视角起伏稳定
beatrun.toolsmenu.camera.stabilizationdesc=开启后可通过让视角起伏保持玩家视线位置居中来减轻晕动症
beatrun.toolsmenu.camera.intensity=视角起伏强度
beatrun.toolsmenu.camera.fov=视野（FOV）
beatrun.toolsmenu.camera.fovdesc=更改你的视野（FOV）

# Tools Menu Gameplay Section
beatrun.toolsmenu.gameplay.name=玩法
beatrun.toolsmenu.gameplay.desc=玩法设置

beatrun.toolsmenu.gameplay.animset=动画组
beatrun.toolsmenu.gameplay.animset1=重制版（MTB）
beatrun.toolsmenu.gameplay.animset2=原版（datae 制作，MTB 修复）

beatrun.toolsmenu.gameplay.catalystcoil=Catalyst 线圈跳动画
beatrun.toolsmenu.gameplay.catalystcoildesc=仅在装备 Runner Hands 时可用；当你装备其他武器时，将改用普通的线圈跳动画

beatrun.toolsmenu.gameplay.quickturnground=地面快速转身
beatrun.toolsmenu.gameplay.quickturngrounddesc=切换：在地面时用副攻击快速转身

beatrun.toolsmenu.gameplay.quickturnhandsonly=仅 Runner Hands 快速转身
beatrun.toolsmenu.gameplay.quickturnhandsonlydesc=切换：仅在使用 "Runner Hands" 时快速转身

beatrun.toolsmenu.gameplay.autohandswitch=自动切换 Runner Hands
beatrun.toolsmenu.gameplay.autohandswitchdesc=在某些移动场景下自动切换到 Runner Hands。

beatrun.toolsmenu.gameplay.puristmode=纯粹模式
beatrun.toolsmenu.gameplay.puristmodedesc=纯粹模式是一个客户端偏好设置，会大幅削弱空中横移（Strafe）的能力，这与《镜之边缘》系列的处理方式一致。\n禁用 = 无限制\n启用 = 空中移动速度降低

beatrun.toolsmenu.gameplay.disablegrapple=禁用抓钩能力
beatrun.toolsmenu.gameplay.disablegrappledesc=切换抓钩能力

beatrun.toolsmenu.gameplay.rollspeedloss=翻滚损失速度
beatrun.toolsmenu.gameplay.rollspeedlossdesc=切换安全翻滚时的速度损失

beatrun.toolsmenu.gameplay.wind=风声效果
beatrun.toolsmenu.gameplay.winddesc=奔跑时播放风声

# Tools Menu Misc Section
beatrun.toolsmenu.misc.name=杂项
beatrun.toolsmenu.misc.desc=杂项设置

beatrun.toolsmenu.misc.propspawn=道具生成
beatrun.toolsmenu.misc.propspawndesc=允许没有管理员权限的玩家生成道具

beatrun.toolsmenu.misc.weaponspawn=武器生成
beatrun.toolsmenu.misc.weaponspawndesc=允许没有管理员权限的玩家生成武器

beatrun.toolsmenu.misc.overdrivemp=多人模式超速（Overdrive）
beatrun.toolsmenu.misc.overdrivempdesc=允许在服务器上使用 Overdrive

beatrun.toolsmenu.misc.healthregen=生命回复
beatrun.toolsmenu.misc.healthregendesc=切换生命回复

beatrun.toolsmenu.misc.lerealisticclimbing=真实攀爬
beatrun.toolsmenu.misc.lerealisticclimbingdesc=未装备 "Runner Hands" 时无法跑墙或攀爬。

# Tools Menu Moves Section
beatrun.toolsmenu.moves.name=动作
beatrun.toolsmenu.moves.desc=动作设置
beatrun.toolsmenu.moves.help=空中按 Ctrl + 右键 可俯冲！\n按 E + 左键 切换 Overdrive。

beatrun.toolsmenu.moves.speedlimit=速度上限
beatrun.toolsmenu.moves.speedlimitdesc=更改玩家速度上限\n默认：325

beatrun.toolsmenu.moves.forcepuristmode=强制纯粹模式
beatrun.toolsmenu.moves.forcepuristmodedesc=强制所有玩家启用纯粹模式

beatrun.toolsmenu.moves.realisticwallrunning="真实" 跑墙
beatrun.toolsmenu.moves.realisticwallrunningdesc=禁用时，开始跑墙不会损失速度

beatrun.toolsmenu.moves.kickglitch=Kick Glitch 版本
beatrun.toolsmenu.moves.kickglitch0=禁用
beatrun.toolsmenu.moves.kickglitch1=原版（速度倍率）
beatrun.toolsmenu.moves.kickglitch2=镜之边缘风格（不可见平台）

beatrun.toolsmenu.moves.quakejump=Quake Jump
beatrun.toolsmenu.moves.quakejumpdesc=切换 Quake Jump 动作\n侧步后立刻按跳跃

beatrun.toolsmenu.moves.sidestep=侧步
beatrun.toolsmenu.moves.sidestepdesc=切换侧步动作\nA/D + 右键

beatrun.toolsmenu.moves.disarm=缴械
beatrun.toolsmenu.moves.disarmdesc=切换对 NPC 缴械能力\n对 NPC 按 使用键

beatrun.toolsmenu.moves.divesettings=俯冲设置

beatrun.toolsmenu.moves.totsugeki=Totsugeki
beatrun.toolsmenu.moves.totsugekidesc=切换 Totsugeki 动作\nQuake Jump 后立刻俯冲

beatrun.toolsmenu.moves.totsugekispam=Totsugeki 连发
beatrun.toolsmenu.moves.totsugekispamdesc=切换是否允许连发 Totsugeki

beatrun.toolsmenu.moves.totsugekiheading=Totsugeki 俯仰
beatrun.toolsmenu.moves.totsugekiheadingdesc=允许在 X 轴（上下）进行 Totsugeki

beatrun.toolsmenu.moves.totsugekidirection=Totsugeki 方向
beatrun.toolsmenu.moves.totsugekidirectiondesc=允许朝另一个方向进行 Totsugeki\n与连发和俯仰配合可实现飞行 =)

beatrun.toolsmenu.moves.totsugekiaudio=Totsugeki 语音
beatrun.toolsmenu.moves.totsugekiaudiodesc=切换 "Totsugeki" 语音

# Tools Menu Gamemodes Section
beatrun.toolsmenu.gamemodes.name=游戏模式
beatrun.toolsmenu.gamemodes.desc=游戏模式设置
beatrun.toolsmenu.gamemodes.error=已有其他游戏模式在运行！

beatrun.toolsmenu.gamemodes.infection=切换感染模式
beatrun.toolsmenu.gamemodes.infectionstarttime=开始前等待
beatrun.toolsmenu.gamemodes.infectiongametime=游戏时长
beatrun.toolsmenu.gamemodes.infectiontime=时间（秒）
beatrun.toolsmenu.gamemodes.datatheft=切换数据盗取模式
beatrun.toolsmenu.gamemodes.deathmatch=切换死斗模式
beatrun.toolsmenu.gamemodes.eventmode=切换活动模式
beatrun.toolsmenu.gamemodes.loadoutseditor=配装编辑器
beatrun.toolsmenu.gamemodes.blacklisteditor=黑名单编辑器

# Tools Menu Extra Section
beatrun.toolsmenu.extra.name=额外
beatrun.toolsmenu.extra.desc=为速通玩家/硬核玩家提供的额外设置

beatrun.toolsmenu.extra.stats=额外统计
beatrun.toolsmenu.extra.statsdesc=除速度表外显示更多统计信息，以帮助完成更难的技巧

beatrun.toolsmenu.extra.speedrunsverif=速通验证统计
beatrun.toolsmenu.extra.speedrunsverifdesc=显示你当前设置的信息（纯粹模式、纯粹跑墙、Kick Glitch 版本）

# Loadouts and Blacklist Editor
beatrun.loadoutseditor.title=配装编辑器
beatrun.loadoutseditor.loadout=配装 %s
beatrun.loadoutseditor.addweapon=添加武器

beatrun.blacklisteditor.title=黑名单（用于随机配装）
beatrun.blacklisteditor.blacklisted=已屏蔽
beatrun.blacklisteditor.allowed=允许

# Checkpoints
beatrun.checkpoints.countdown1=准备
beatrun.checkpoints.countdown2=预备
beatrun.checkpoints.countdown3=开始！

# DataTheft
beatrun.datatheft.name=数据盗取（%s）
beatrun.datatheft.start=数据盗取！击杀玩家以收集数据，并将数据存入银行

# Deathmatch
beatrun.deathmatch.name=死斗
beatrun.deathmatch.start=死斗！击杀玩家获得积分！

# Eventmode
beatrun.eventmode.name=[活动模式]
beatrun.eventmode.start=活动已经开始！请遵循管理人员的指示。
beatrun.eventmode.memberlabel=成员
beatrun.eventmode.memberhud=你正在参与！
beatrun.eventmode.suspendedlabel=停赛
beatrun.eventmode.suspendedhud=你已被停赛！
beatrun.eventmode.managerlabel=管理者
beatrun.eventmode.managerhud=[管理者]

# Infection
beatrun.infection.name=感染
beatrun.infection.infectedtext=(感染者)
beatrun.infection.humantext=(人类)
beatrun.infection.start=感染模式！触碰其他玩家即可感染他们\n%s 名玩家将在 %ss 后被感染
beatrun.infection.nosurvivors=无人...
beatrun.infection.infected=已被感染！
beatrun.infection.infectedby=感染了
beatrun.infection.award=你因存活获得了 200 XP！
beatrun.infection.awardinfected=你因出生为感染者获得了 100 XP！
beatrun.infection.end=游戏结束！\n幸存者：%s\n15 秒后重新开始

# Server ConVars
beatrun.randomloadoutsdesc=更改死斗与数据盗取的随机配装
beatrun.randombeatrunloadouts=自定义配装
beatrun.randommwloadouts=MW 基础配装
beatrun.randomarc9loadouts=ARC9 配装
beatrun.randomarccwloadouts=ARCCW 配装
beatrun.randomtfaloadouts=TFA 配装
