# Misc
beatrun.misc.yes=Ja
beatrun.misc.no=Nein
beatrun.misc.ok=OK
beatrun.misc.cancel=Abbrechen
beatrun.misc.noclipdetected=Noclip bemerkt! Respawne um den Kurs neu zu starten
beatrun.misc.checkconsole=Überprüfe die Konsole!

# Addon Warning
beatrun.addonwarning.warntext=BEACHTEN\nBitte die folgenden Addons deaktivieren, bevor Sie spielen oder auf Github ein Problem melden:
beatrun.addonwarning.quitbutton=Zurück zum Hauptmenü
beatrun.addonwarning.play=Spielen
beatrun.addonwarning.conflictfound=KONFLIGIERENDE ADDONS GEFUNDEN

# Build Mode HUD
beatrun.buildmodehud.info=Verzeichnis: %s\nAusgewählt: %s\nWinkel: %s
beatrun.buildmodehud.props=Menü / Gegenstände
beatrun.buildmodehud.entities=Menü / Entitäten
beatrun.buildmodehud.drag=Ziehen (G)
beatrun.buildmodehud.copy=Kopieren (SHIFT+D)
beatrun.buildmodehud.delete=Löschen (DEL/BCKSPC)
beatrun.buildmodehud.highlight=Hervorheben (T)
beatrun.buildmodehud.select=Auswählen
beatrun.buildmodehud.zipline=Seilrutsche (SHIFT = 2-Way)

# ConVars
beatrun.convars.hudxp=Gesamte Menge an XP in der Nähe des Spielernamens anzeigen
beatrun.convars.hudsway=HUD Schwanken anzeigen
beatrun.convars.huddynamic=HUD nicht anzeigen während der Bewegung
beatrun.convars.hudhidden=Blendet den Großteil des HUD aus
beatrun.convars.hudreticle=Fadenkreuz anzeigen
beatrun.convars.hudtextcolor=HUD Text Farbe\nStandard: 255 255 255 255
beatrun.convars.hudcornercolor=HUD Ecken Farbe\nStandard: 20 20 20 100
beatrun.convars.hudfloatxpcolor=HUD schwebende XP Farbe\nStandard: 255 255 255 255
beatrun.convars.nametags=Spielernamen anzeigen
beatrun.convars.apikey=API-Schlüssel
beatrun.convars.domain=Domain von der Kurs-Datenbank
beatrun.convars.theme=Design für das Kursmenü ändern. "Dunkel" und "Hell" sind verfügbar.
beatrun.convars.viewbob=Viewbob Intensität
beatrun.convars.viewbobstabilization=Diese Option aktivieren, um Reisekrankheit zu reduzieren, indem das Viewbobbing der Blickposition des Spielers zentriert bleibt
beatrun.convars.fov=Ändert die Sichtweite des Spielers
beatrun.convars.cpsave=Beim Respawning während eines Kurses wird man zum letzten getroffenen Checkpoint zurück teleportiert
beatrun.convars.faststart=Kürzerer Start Countdown
beatrun.convars.disablegrapple=Schaltet die Greiffähigkeit ein/aus
beatrun.convars.puristmode=Der Puristenmodus ist eine clientseitige Einstellung, die das Seitwärts Laufen in der Luft stark einschränkt. So wird dies in ME-Spielen gehandhabt.\n0 = Keine Einschränkungen\n1 = Reduzierte Bewegungsgeschwindigkeit in der Luft
beatrun.convars.quickturnground=Aktiviert/Deaktiviert die Schnelldrehung mit Sekundärangriff am Boden.
beatrun.convars.quickturnhandsonly=Schaltet Schnelldrehungen nur mit "Runner Hands" um
beatrun.convars.showspeedometer=Tachometer-Sichtbarkeit umschalten
beatrun.convars.speedometermode=Tachometer-Modus ändern

# HUD
beatrun.hud.course=Kurs: %s
beatrun.hud.freeplay=Freispiel
beatrun.hud.lvl=Level: %s
beatrun.hud.infector=Infektor

# Courses Menu
beatrun.coursesmenu.save=Speichern
beatrun.coursesmenu.start=Start
beatrun.coursesmenu.upload=Hochladen
beatrun.coursesmenu.upload.confirm=Sind Sie sicher, dass sie diesen Kurs in die Datenbank hochladen möchten?
beatrun.coursesmenu.delete=Löschen
beatrun.coursesmenu.delete.confirm=Sind Sie sicher, dass sie diesen Kurs löschen möchten?
beatrun.coursesmenu.downloads=Downloads: %d
beatrun.coursesmenu.uploadedat=Hochgeladen am: %s
beatrun.coursesmenu.copied=In die Zwischenablage kopiert

beatrun.coursesmenu.localpage=Lokal
beatrun.coursesmenu.localpage.savecourse=Kurs speichern
beatrun.coursesmenu.localpage.buildmode=Bau-Modus an/ausschalten
beatrun.coursesmenu.localpage.freeplay=Zum Freispiel zurückkehren
beatrun.coursesmenu.localpage.savedcourses=Gespeicherte Kurse für %s
beatrun.coursesmenu.localpage.nosavedcourses=Keine gespeicherten Kurse gefunden...

beatrun.coursesmenu.onlinepage=Online
beatrun.coursesmenu.onlinepage.currentmap=Nur aktuelle Karte
beatrun.coursesmenu.onlinepage.notcurrentmap=Alle Kurse
beatrun.coursesmenu.onlinepage.search.placeholder=Kurse suchen...
beatrun.coursesmenu.onlinepage.start=Kurs starten
beatrun.coursesmenu.onlinepage.start.message=Sie haben diese Karte nicht abonniert. Wenn Sie den Kurs starten, könnten Sie feststecken. Würden sie gerne abonnieren?
beatrun.coursesmenu.onlinepage.openworkshop=Workshop öffnen
beatrun.coursesmenu.onlinepage.iknowwhatimdoing=Ich weiß, was ich tue
beatrun.coursesmenu.onlinepage.download=Herunterladen
beatrun.coursesmenu.onlinepage.overwrite=Überschreiben?
beatrun.coursesmenu.onlinepage.overwrite.confirm=Die Datei dieses Kurses existiert bereits. Überschreiben?

beatrun.coursesmenu.profilepage=Profil
beatrun.coursesmenu.profilepage.register=Registrierungsseite im Steam Overlay öffnen
beatrun.coursesmenu.profilepage.copylink=Registrierungslink kopieren
beatrun.coursesmenu.profilepage.message=Sie brauchen einen API-Schlüssel um Kurse hochzuladen\nDer Knopf unten wird eine Webseite im Steam Overlay öffnen für die Registrierung,\nWir werden nur deine SteamID und den Nutzernamen verwenden!\nWir sammeln keine anderen Informationen!\nWenn du kein Overlay hast oder es nicht funktioniert, Kopiere die Adresse und öffne sie in deinem Webbrowser.
beatrun.coursesmenu.profilepage.key=API-Schlüssel: %s
beatrun.coursesmenu.profilepage.changekey=API-Schlüssel ändern
beatrun.coursesmenu.profilepage.changekey.placeholder=Neuen API-Schlüssel eingeben...
beatrun.coursesmenu.profilepage.stats=Gesamtanzahl an Uploads: %d | Gesamtanzahl an Downloads: %d
beatrun.coursesmenu.profilepage.nouploadedcourses=Sie haben noch keine Kurse hochgeladen...

beatrun.coursesmenu.settings=Einstellungen
beatrun.coursesmenu.settings.domain=Kurs Datenbank Domain
beatrun.coursesmenu.settings.theme=Design

beatrun.coursesmenu.themes.dark=Dunkel
beatrun.coursesmenu.themes.light=Hell

beatrun.coursesmenu.save.placeholder=Geben Sie einen Kursnamen ein...
beatrun.coursesmenu.save.maxspeedlock=Maximale Geschwindigkeit begrenzen

# Courses Menu Notifications
beatrun.coursesmenu.notification.openconsole=Fehler, Konsole überprüfen

beatrun.coursesmenu.notification.fetch.failed=Daten konnten nicht vom/zum Server gesendet werden, Konsole überprüfen
beatrun.coursesmenu.notification.upload.success=Upload erfolgreich, Konsole überprüfen

beatrun.coursesmenu.notification.save.failed=Kurs konnte nicht zu einer Datei abgespeichert werden
beatrun.coursesmenu.notification.save.success=Kurs abgespeichert in data/%s

beatrun.coursesmenu.notification.read.failed=Datei konnte nicht geöffnet/gelesen werden

beatrun.coursesmenu.notification.startingcourse=Starte Kurs %s...

beatrun.coursesmenu.notification.nokey=API-Schlüssel fehlt

# Tools Menu
beatrun.toolsmenu.client=Klient
beatrun.toolsmenu.server=Server
beatrun.toolsmenu.extra=Extra

# Tools Menu Courses Section
beatrun.toolsmenu.courses.name=Kurse
beatrun.toolsmenu.courses.desc=Kurs Einstellungen

beatrun.toolsmenu.courses.raceyourghost=Rennen mit einem Geist
beatrun.toolsmenu.courses.raceyourghostdesc=Fahre ein Rennen gegen einen Geist, der deine beste Streckenzeit spielt.

beatrun.toolsmenu.courses.faststart=Schnellstart
beatrun.toolsmenu.courses.faststartdesc=Kürzerer Countdown zu Beginn eines Kurses

beatrun.toolsmenu.courses.checkpointsave=Am Checkpoint speichern
beatrun.toolsmenu.courses.checkpointsavedesc=In Kursen am zuletzt getroffenen Checkpoint Respawnen

# Tools Menu HUD Section
beatrun.toolsmenu.hud.name=HUD
beatrun.toolsmenu.hud.desc=HUD Einstellungen

beatrun.toolsmenu.hud.dynamic=Dynamisches HUD
beatrun.toolsmenu.hud.dynamicdesc=Versteckt das HUD während der Bewegung

beatrun.toolsmenu.hud.sway=HUD Schwanken
beatrun.toolsmenu.hud.swaydesc=Schaltet HUD Schwanken ein/aus

beatrun.toolsmenu.hud.nametags=Namen anzeigen
beatrun.toolsmenu.hud.nametagsdesc=Schaltet Namen über Spielern ein/aus

beatrun.toolsmenu.hud.hudxp=HUD XP Anzeigen
beatrun.toolsmenu.hud.hudxpdesc=Zeigt die Gesamt-XP an
beatrun.toolsmenu.hud.showspeedometer=Tachometer anzeigen
beatrun.toolsmenu.hud.showspeedometerdesc=Zeigt den Tachometer auf dem HUD an

beatrun.toolsmenu.hud.speedometermode=Tachometer-Modus
beatrun.toolsmenu.hud.speedometermode1=km/h
beatrun.toolsmenu.hud.speedometermode2=mph
beatrun.toolsmenu.hud.speedometermode3=hu/h

beatrun.toolsmenu.hud.showSpeedometer=Tachometer anzeigen
beatrun.toolsmenu.hud.showSpeedometerDesc=Zeigt den Tachometer auf dem HUD an (das HUD auszuschalten betrifft nicht die Sichtbarkeit)

beatrun.toolsmenu.hud.keystrokes=Tastatureingaben anzeigen
beatrun.toolsmenu.hud.keystrokesdesc=Zeigt die gedrückten Tasten an

beatrun.toolsmenu.hud.keystrokes_x_offset=Tastatureingaben X Versatz
beatrun.toolsmenu.hud.keystrokes_y_offset=Tastatureingaben Y Versatz

beatrun.toolsmenu.hud.keystrokes_corner=Tastatureingaben Ausrichtung
beatrun.toolsmenu.hud.keystrokes_corner1=Oben links
beatrun.toolsmenu.hud.keystrokes_corner2=Oben rechts
beatrun.toolsmenu.hud.keystrokes_corner3=Unten links
beatrun.toolsmenu.hud.keystrokes_corner4=Unten rechts

beatrun.toolsmenu.hud.hidden=HUD Sichtbarkeit
beatrun.toolsmenu.hud.hidden0=Anzeigen
beatrun.toolsmenu.hud.hidden1=Nur Spielmodus und Geschwindigkeit
beatrun.toolsmenu.hud.hidden2=Ausblenden

beatrun.toolsmenu.hud.textcolor=HUD Text Farbe
beatrun.toolsmenu.hud.cornercolor=HUD Ecken Farbe
beatrun.toolsmenu.hud.floatxpcolor=HUD schwebende XP Farbe

# Tools Menu Camera Section
beatrun.toolsmenu.camera.name=Kamera
beatrun.toolsmenu.camera.desc=Kamera Einstellungen

beatrun.toolsmenu.camera.colormodifyfilter=Farbfilter deaktivieren
beatrun.toolsmenu.camera.colormodifyfilterdesc=Deaktiviert die Farbfilter
beatrun.toolsmenu.camera.stabilization=Viewbob Stabilisierung
beatrun.toolsmenu.camera.stabilizationdesc=Diese Option aktivieren, um Reisekrankheit zu reduzieren, indem das Viewbobbing der Blickposition des Spielers zentriert bleibt
beatrun.toolsmenu.camera.intensity=Viewbob Intensität
beatrun.toolsmenu.camera.fov=Sichtweite
beatrun.toolsmenu.camera.fovdesc=Ändert die Sichtweite

# Tools Menu Gameplay Section
beatrun.toolsmenu.gameplay.name=Gameplay
beatrun.toolsmenu.gameplay.desc=Gameplay Einstellungen

beatrun.toolsmenu.gameplay.animset=Animationen Set
beatrun.toolsmenu.gameplay.animset1=Reanimated (von MTB)
beatrun.toolsmenu.gameplay.animset2=Original (von datae, behoben von MTB)

beatrun.toolsmenu.gameplay.catalystcoil=Catalyst Sprung Animation
beatrun.toolsmenu.gameplay.catalystcoildesc=Kann nur benutzt werden, während "Runner Hands" ausgerüstet ist. Die normale Sprunganimation wird verwendet, wenn andere Waffen ausgerüstet sind.

beatrun.toolsmenu.gameplay.quickturnground=Schnelldrehung am Boden
beatrun.toolsmenu.gameplay.quickturngrounddesc=Aktiviert/Deaktiviert die Schnelldrehung mit Sekundärangriff am Boden.

beatrun.toolsmenu.gameplay.quickturnhandsonly=Schnelldrehungen nur mit Händen
beatrun.toolsmenu.gameplay.quickturnhandsonlydesc=Schaltet Schnelldrehungen nur mit "Runner Hands" um

beatrun.toolsmenu.gameplay.autohandswitch=Automatisches Hand Wechseln
beatrun.toolsmenu.gameplay.autohandswitchdesc=Wechselt automatisch zu "Runner Hands" während bestimmten Bewegungsszenarien.

beatrun.toolsmenu.gameplay.puristmode=Puristen Modus
beatrun.toolsmenu.gameplay.puristmodedesc=Der Puristenmodus ist eine clientseitige Einstellung, die das Seitwärts Laufen in der Luft stark einschränkt. So wird dies in ME-Spielen gehandhabt.\n = Keine Einschränkungen\n = Reduzierte Bewegungsgeschwindigkeit in der Luft

beatrun.toolsmenu.gameplay.disablegrapple=Greiffähigkeit deaktivieren
beatrun.toolsmenu.gameplay.disablegrappledesc=Schaltet die Greiffähigkeit ein/aus

beatrun.toolsmenu.gameplay.rollspeedloss=Geschwindigkeit beim Rollen verlieren
beatrun.toolsmenu.gameplay.rollspeedlossdesc=Schaltet Verlust von Geschwindigkeit beim Abrollen ein/aus

beatrun.toolsmenu.gameplay.wind=Wind Effekt
beatrun.toolsmenu.gameplay.winddesc=Wind Geräusche während dem Rennen

# Tools Menu Misc Section
beatrun.toolsmenu.misc.name=Sonstiges
beatrun.toolsmenu.misc.desc=Sonstige Einstellungen

beatrun.toolsmenu.misc.propspawn=Gegenstände erzeugen
beatrun.toolsmenu.misc.propspawndesc=Erlaubt Spielern ohne Admin Rechte Gegenstände zu erzeugen

beatrun.toolsmenu.misc.weaponspawn=Waffen erzeugen
beatrun.toolsmenu.misc.weaponspawndesc=Erlaubt Spielern ohne Admin Rechte Waffen zu erzeugen

beatrun.toolsmenu.misc.overdrivemp=Overdrive im Mehrspieler
beatrun.toolsmenu.misc.overdrivempdesc=Erlaubt die Nutzung von Overdrive auf dem Server

beatrun.toolsmenu.misc.healthregen=Gesundheitsregeneration
beatrun.toolsmenu.misc.healthregendesc=Schaltet die Gesundheitsregeneration ein/aus

beatrun.toolsmenu.misc.lerealisticclimbing=Realistisches Klettern
beatrun.toolsmenu.misc.lerealisticclimbingdesc=Deaktiviert den Wandlauf und das Klettern, es sei denn, "Runner Hands" sind ausgerüstet.

# Tools Menu Moves Section
beatrun.toolsmenu.moves.name=Bewegungen
beatrun.toolsmenu.moves.desc=Bewegungseinstellungen
beatrun.toolsmenu.moves.help=Sie können mit Strg + RMT einen Salto in der Luft machen!\nOverdrive lässt sich mit E + LMT aktivieren.

beatrun.toolsmenu.moves.speedlimit=Geschwindigkeitsbegrenzung
beatrun.toolsmenu.moves.speedlimitdesc=Ändert die begrenzte Geschwindigkeit des Spielers\nStandard: 325

beatrun.toolsmenu.moves.forcepuristmode=Erzwingen des Puristen Modus
beatrun.toolsmenu.moves.forcepuristmodedesc=Erzwingt den Puristen Modus für alle Spieler

beatrun.toolsmenu.moves.realisticwallrunning="Realistischer" Wandlauf
beatrun.toolsmenu.moves.realisticwallrunningdesc=Sie verlieren keine Geschwindigkeit beim Start eines Wandlaufes, wenn deaktiviert

beatrun.toolsmenu.moves.kickglitch=Kick Glitch Version
beatrun.toolsmenu.moves.kickglitch0=Deaktiviert
beatrun.toolsmenu.moves.kickglitch1=Original (Geschwindigkeitsmultiplikator)
beatrun.toolsmenu.moves.kickglitch2=Mirror's Edge-Stil (Unsichtbare Plattform)

beatrun.toolsmenu.moves.quakejump=Quake Jump
beatrun.toolsmenu.moves.quakejumpdesc=De/Aktiviert die Quake Jump Bewegung\nDirekt nach dem Side Step springen

beatrun.toolsmenu.moves.sidestep=Side Step
beatrun.toolsmenu.moves.sidestepdesc=De/Aktiviert die Side Step Bewegung\nA/D + RMT

beatrun.toolsmenu.moves.disarm=Entwaffnen
beatrun.toolsmenu.moves.disarmdesc=Aktiviert die Fähigkeit einen NPC zu entwaffnen\nInteraktionstaste auf einen NPC drücken

beatrun.toolsmenu.moves.divesettings=Salto Einstellungen

beatrun.toolsmenu.moves.totsugeki=Totsugeki
beatrun.toolsmenu.moves.totsugekidesc=De/Aktiviert die Totsugeki Bewegung\nDirekt nach dem Quake Jump springen

beatrun.toolsmenu.moves.totsugekispam=Totsugeki Spam
beatrun.toolsmenu.moves.totsugekispamdesc=De/Aktiviert die Fähigkeit Totsugeki zu spammen

beatrun.toolsmenu.moves.totsugekiheading=Totsugeki Steuerkurs
beatrun.toolsmenu.moves.totsugekiheadingdesc=Erlaubt den Totsugeki auf der x-Achse (oben/unten)

beatrun.toolsmenu.moves.totsugekidirection=Totsugeki Richtung
beatrun.toolsmenu.moves.totsugekidirectiondesc=Erlaubt den Totsugeki in eine andere Richtung\nWenn man den Spam und den Steuerkurs damit kombiniert kann man Fliegen =)

beatrun.toolsmenu.moves.totsugekiaudio=Totsugeki Ton
beatrun.toolsmenu.moves.totsugekiaudiodesc=De/Aktiviert die "Totsugeki" Stimme

# Tools Menu Gamemodes Section
beatrun.toolsmenu.gamemodes.name=Spielmodi
beatrun.toolsmenu.gamemodes.desc=Spielmodus Einstellungen
beatrun.toolsmenu.gamemodes.error=Ein anderer Spielmodus läuft!

beatrun.toolsmenu.gamemodes.infection=Infection Spielmodus an/ausschalten
beatrun.toolsmenu.gamemodes.infectionstarttime=Zeit vor dem Start
beatrun.toolsmenu.gamemodes.infectiongametime=Gesamtlänge des Spieles
beatrun.toolsmenu.gamemodes.infectiontime=Zeit in Sekunden
beatrun.toolsmenu.gamemodes.datatheft=Data Theft Spielmodus an/ausschalten
beatrun.toolsmenu.gamemodes.deathmatch=Deathmatch Spielmodus an/ausschalten
beatrun.toolsmenu.gamemodes.eventmode=Ereignis Spielmodus an/ausschalten

# Tools Menu Extra Section
beatrun.toolsmenu.extra.name=Extra
beatrun.toolsmenu.extra.desc=Extra Einstellungen für Speedrunner/Schwitzer

beatrun.toolsmenu.extra.stats=Extra Statistiken
beatrun.toolsmenu.extra.statsdesc=Zeigt Extra Statistiken abgesehen vom Tachometer an, um mehr Informationen anzuzeigen, um bei schwereren Tricks zu helfen

beatrun.toolsmenu.extra.speedrunsverif=Speedrun Verifizierungs Statistiken
beatrun.toolsmenu.extra.speedrunsverifdesc=Zeigt Informationen über die aktuellen Einstellungen an (Puristen Modus, Puristen Wandlauf und die Kick Glitch version)

# Checkpoints
beatrun.checkpoints.countdown1=Auf die Plätze
beatrun.checkpoints.countdown2=Fertig
beatrun.checkpoints.countdown3=LOS!

# DataTheft
beatrun.datatheft.name=Data Theft (%s)
beatrun.datatheft.start=Data Theft! Töte Spieler, um Daten zu sammeln, zahle Daten bei Banken ein

# Deathmatch
beatrun.deathmatch.name=Deathmatch
beatrun.deathmatch.start=Deathmatch! Töte Spieler, um Punkte zu bekommen!

# Eventmode
beatrun.eventmode.name=[EVENT MODE]
beatrun.eventmode.start=Das Ereignis hat begonnen! Befolge die Anweisungen der Verwaltung.
beatrun.eventmode.memberlabel=Mitglied
beatrun.eventmode.memberhud=Du machst mit!
beatrun.eventmode.suspendedlabel=Suspendiert
beatrun.eventmode.suspendedhud=Du bist suspendiert!
beatrun.eventmode.managerlabel=Verwalter
beatrun.eventmode.managerhud=[VERWALTER]

# Infection
beatrun.infection.name=Infection
beatrun.infection.infectedtext=(Infiziert)
beatrun.infection.humantext=(Mensch)
beatrun.infection.start=Infection! Berühre andere Spieler, um sie zu infizieren\n%s Spieler werden infiziert in %ss
beatrun.infection.nosurvivors=Keine...
beatrun.infection.infected=wurde infiziert!
beatrun.infection.infectedby=infizierte
beatrun.infection.award=Dir wurden 200 XP fürs Überleben gutgeschrieben!
beatrun.infection.awardinfected=Dir wurden 100 XP für das spawnen als Infizierter gutgeschrieben!
beatrun.infection.end=Das Spiel ist vorbei!\nÜberlebende: %s\nNeue Runde in 15s

# Server ConVars
beatrun.randomloadoutsdesc=Ändert zufällige Loadouts für Deathmatch und DataTheft
beatrun.randombeatrunloadouts=Beatrun Loadouts
beatrun.randommwloadouts=MW Base Loadouts
beatrun.randomarc9loadouts=ARC9 Loadouts
beatrun.randomarccwloadouts=ARCCW Loadouts
beatrun.randomtfaloadouts=TFA Loadouts
