# Misc
beatrun.misc.yes=Так
beatrun.misc.no=Ні
beatrun.misc.ok=Ок
beatrun.misc.cancel=Скасувати
beatrun.misc.add=Додати
beatrun.misc.delete=Видалити
beatrun.misc.save=Зберегти
beatrun.misc.noclipdetected=Виявлено NoClip! Натисніть R щоб почати заново
beatrun.misc.checkconsole=Перевірте консоль!

# Build Mode HUD
beatrun.buildmodehud.info=Вказівник: %s\nВибрано: %s\nКут: %s
beatrun.buildmodehud.props=Меню / Пропи
beatrun.buildmodehud.entities=Меню / Ентіті
beatrun.buildmodehud.drag=Перемістити (G)
beatrun.buildmodehud.copy=Копіювати (SHIFT+D)
beatrun.buildmodehud.delete=Видалити (DEL/BCKSPC)
beatrun.buildmodehud.highlight=Підсвітити (T)
beatrun.buildmodehud.select=Вибрати
beatrun.buildmodehud.zipline=Зіплайн (SHIFT = двосторонній)

# ConVars
beatrun.convars.hudxp=Показати весь досвід біля ніку
beatrun.convars.hudsway=Відображати похитування HUD
beatrun.convars.huddynamic=Приховати HUD під час руху
beatrun.convars.hudhidden=Приховати HUD
beatrun.convars.hudreticle=Показати точку
beatrun.convars.hudtextcolor=Колір тексту в HUD\nDefault: 255 255 255 255
beatrun.convars.hudcornercolor=Колір краю в HUD\nDefault: 20 20 20 100
beatrun.convars.hudfloatxpcolor=Колір спливаючого XP в HUD\nDefault: 255 255 255 255
beatrun.convars.nametags=Показати ніки над гравцями
beatrun.convars.apikey=API ключ
beatrun.convars.domain=Домен бази курсів
beatrun.convars.theme=Змінює тему меню курсів. Доступні "Dark" і "Light".
beatrun.convars.viewbob=Інтенсивність похитування камери
beatrun.convars.viewbobstabilization=Увімкніть щоб знизити похитування камери центруючи її
beatrun.convars.fov=Кут огляду гравця
beatrun.convars.cpsave=Респавн у курсах відправляє на останню контрольну точку
beatrun.convars.faststart=Швидкий відлік на початку курсу
beatrun.convars.disablegrapple=Перемикає гак-кішку
beatrun.convars.puristmode=Режим Purist це клієнтський параметр який сильно знижує рух гравця вбік перебуваючи в повітрі, прямо як в оригінальній ME.\n0 = Без обмежень\n1 = Знижує рух гравця в повітрі вбік
beatrun.convars.quickturnground=Перемикає Quickturn перебуваючи на землі
beatrun.convars.quickturnhandsonly=Перемикає Quickturn лише з "Runner Hands"
beatrun.convars.showspeedometer=Перемикає спідометр
beatrun.convars.speedometermode=Змінює режим спідометра

# HUD
beatrun.hud.course=Курс: %s
beatrun.hud.freeplay=Вільна гра
beatrun.hud.lvl=Рівень: %s
beatrun.hud.infector=Заражений

# Courses Menu
beatrun.coursesmenu.save=Зберегти
beatrun.coursesmenu.start=Запустити
beatrun.coursesmenu.upload=Завантажити
beatrun.coursesmenu.upload.confirm=Ви впевнені що хочете завантажити цей курс у базу?
beatrun.coursesmenu.delete=Видалити
beatrun.coursesmenu.delete.confirm=Ви впевнені що хочете видалити цей курс?
beatrun.coursesmenu.downloads=Завантажень: %d
beatrun.coursesmenu.uploadedat=Завантажено: %s
beatrun.coursesmenu.copied=Скопійовано в буфер обміну

beatrun.coursesmenu.domain.change=Змінити адресу бази
beatrun.coursesmenu.domain.change.placeholder=Введіть адресу бази курсів (без "https://" та "/" в кінці)

beatrun.coursesmenu.localpage=Локальні
beatrun.coursesmenu.localpage.savecourse=Зберегти курс
beatrun.coursesmenu.localpage.buildmode=Перемкнути режим будівництва
beatrun.coursesmenu.localpage.freeplay=Повернутися у Freeplay
beatrun.coursesmenu.localpage.savedcourses=Збережені курси для %s
beatrun.coursesmenu.localpage.nosavedcourses=Курсів не знайдено...

beatrun.coursesmenu.onlinepage=Онлайн
beatrun.coursesmenu.onlinepage.currentmap=Лише Поточна Карта
beatrun.coursesmenu.onlinepage.notcurrentmap=Всі Курси
beatrun.coursesmenu.onlinepage.search.placeholder=Пошук по курсах...
beatrun.coursesmenu.onlinepage.start=Запустити курс
beatrun.coursesmenu.onlinepage.start.message=Ви не підписані на цю карту. Якщо запустити цей курс, він буде зламаний. Хочете підписатися на карту?
beatrun.coursesmenu.onlinepage.openworkshop=Відкрити Workshop
beatrun.coursesmenu.onlinepage.iknowwhatimdoing=Я знаю що роблю
beatrun.coursesmenu.onlinepage.download=Завантажити
beatrun.coursesmenu.onlinepage.overwrite=Перезаписати?
beatrun.coursesmenu.onlinepage.overwrite.confirm=Файл цього курсу вже існує. Перезаписати?

beatrun.coursesmenu.profilepage=Профіль
beatrun.coursesmenu.profilepage.register=Відкрити вікно реєстрації в оверлеї Steam
beatrun.coursesmenu.profilepage.copylink=Скопіювати посилання для реєстрації
beatrun.coursesmenu.profilepage.message=Вам потрібен API ключ для завантаження курсів у базу\nКнопка нижче відкриє сторінку реєстрації в оверлеї Steam,\nзвідти ми візьмемо лише ваш SteamID та нік!\nБільше ми не збираємо жодну інформацію!\nЯкщо у вас немає оверлею або він не працює, скопіюйте сторінку та відкрийте в браузері
beatrun.coursesmenu.profilepage.key=API Ключ: %s
beatrun.coursesmenu.profilepage.changekey=Змінити API ключ
beatrun.coursesmenu.profilepage.changekey.placeholder=Введіть новий API ключ...
beatrun.coursesmenu.profilepage.stats=Ваших завантажень: %d | Всього скачувань за вашими курсами: %d
beatrun.coursesmenu.profilepage.nouploadedcourses=Ви ще не завантажували курси...

beatrun.coursesmenu.settings=Налаштування
beatrun.coursesmenu.settings.domain=Адреса бази курсів
beatrun.coursesmenu.settings.theme=Тема

beatrun.coursesmenu.themes.dark=Темна
beatrun.coursesmenu.themes.light=Світла

beatrun.coursesmenu.save.placeholder=Введіть назву курсу...
beatrun.coursesmenu.save.maxspeedlock=Обмежити макс. швидкість

# Courses Menu Notifications
beatrun.coursesmenu.notification.openconsole=Помилка, перевірте консоль

beatrun.coursesmenu.notification.fetch.failed=Помилка отримання або надсилання даних серверу, перевірте консоль
beatrun.coursesmenu.notification.upload.success=Успішно завантажено, перевірте консоль

beatrun.coursesmenu.notification.save.failed=Помилка збереження курсу в файл
beatrun.coursesmenu.notification.save.success=Курс збережено в data/%s

beatrun.coursesmenu.notification.read.failed=Помилка відкриття/читання файлу

beatrun.coursesmenu.notification.startingcourse=Запускаю курс %s...

beatrun.coursesmenu.notification.nokey=API ключ не існує

# Tools Menu
beatrun.toolsmenu.client=Клієнт
beatrun.toolsmenu.server=Сервер
beatrun.toolsmenu.extra=Додатково

# Tools Menu Courses Section
beatrun.toolsmenu.courses.name=Курси
beatrun.toolsmenu.courses.desc=Налаштування курсів

beatrun.toolsmenu.courses.raceyourghost=Гонка з привидом
beatrun.toolsmenu.courses.raceyourghostdesc=Гонка з привидом вашого найкращого часу в поточному курсі

beatrun.toolsmenu.courses.faststart=Швидкий старт
beatrun.toolsmenu.courses.faststartdesc=Швидкий відлік на початку курсу

beatrun.toolsmenu.courses.checkpointsave=Збереження на контр. точках
beatrun.toolsmenu.courses.checkpointsavedesc=Респавн на останній контрольній точці

# Tools Menu HUD Section
beatrun.toolsmenu.hud.name=HUD
beatrun.toolsmenu.hud.desc=Налаштування HUD

beatrun.toolsmenu.hud.dynamic=Динамічний HUD
beatrun.toolsmenu.hud.dynamicdesc=Ховає HUD під час руху

beatrun.toolsmenu.hud.sway=Похитування HUD
beatrun.toolsmenu.hud.swaydesc=Похитує HUD при різноманітних діях

beatrun.toolsmenu.hud.nametags=Показати Ніки
beatrun.toolsmenu.hud.nametagsdesc=Показує ніки над гравцями

beatrun.toolsmenu.hud.hudxp=Показати XP в HUD
beatrun.toolsmenu.hud.hudxpdesc=Показує весь XP в HUD

beatrun.toolsmenu.hud.showspeedometer=Показати спідометр
beatrun.toolsmenu.hud.showspeedometerdesc=Показує спідометр в HUD

beatrun.toolsmenu.hud.speedometermode=Режим спідометра
beatrun.toolsmenu.hud.speedometermode1=км/год
beatrun.toolsmenu.hud.speedometermode2=миль/год
beatrun.toolsmenu.hud.speedometermode3=hu/год

beatrun.toolsmenu.hud.keystrokes=Показувати клавіші
beatrun.toolsmenu.hud.keystrokesdesc=Показує натискання клавіш в HUD

beatrun.toolsmenu.hud.keystrokes_x_offset=Keystrokes X Зсув
beatrun.toolsmenu.hud.keystrokes_y_offset=Keystrokes Y Зсув

beatrun.toolsmenu.hud.keystrokes_corner=Keystrokes Вирівнювання
beatrun.toolsmenu.hud.keystrokes_corner1=Зліва-зверху
beatrun.toolsmenu.hud.keystrokes_corner2=Справа-зверху
beatrun.toolsmenu.hud.keystrokes_corner3=Зліва-знизу
beatrun.toolsmenu.hud.keystrokes_corner4=Справа-знизу

beatrun.toolsmenu.hud.hidden=Видимість HUD
beatrun.toolsmenu.hud.hidden0=Показати
beatrun.toolsmenu.hud.hidden1=Лише режим і швидкість
beatrun.toolsmenu.hud.hidden2=Приховати

beatrun.toolsmenu.hud.textcolor=Колір Тексту в HUD
beatrun.toolsmenu.hud.cornercolor=Колір Краю в HUD
beatrun.toolsmenu.hud.floatxpcolor=Колір Спливаючого XP в HUD

# Tools Menu Camera Section
beatrun.toolsmenu.camera.name=Камера
beatrun.toolsmenu.camera.desc=Налаштування камери

beatrun.toolsmenu.camera.colormodifyfilter=Вимкнути фільтри кольору
beatrun.toolsmenu.camera.colormodifyfilterdesc=Вимикає фільтри кольору
beatrun.toolsmenu.camera.stabilization=Стабілізація похитування
beatrun.toolsmenu.camera.stabilizationdesc=Увімкніть щоб знизити похитування камери центруючи її
beatrun.toolsmenu.camera.intensity=Інтенсивність похитування камери
beatrun.toolsmenu.camera.fov=Кут Огляду
beatrun.toolsmenu.camera.fovdesc=Змінює ваш Кут Огляду

# Tools Menu Gameplay Section
beatrun.toolsmenu.gameplay.name=Геймплей
beatrun.toolsmenu.gameplay.desc=Налаштування геймплею

beatrun.toolsmenu.gameplay.animset=Набір анімацій
beatrun.toolsmenu.gameplay.animset1=Reanimated (від MTB)
beatrun.toolsmenu.gameplay.animset2=Оригінал (від datae, фікси від MTB)

beatrun.toolsmenu.gameplay.catalystcoil=Анімація стрибка в стилі Catalyst
beatrun.toolsmenu.gameplay.catalystcoildesc=Анімація стрибка з CTRL виглядатиме приблизно як в Catalyst.\nЛише коли використовуються Runner Hands.

beatrun.toolsmenu.gameplay.quickturnground=Quickturn на Землі
beatrun.toolsmenu.gameplay.quickturngrounddesc=Перемикає Quickturn перебуваючи на землі (швидкий розворот)

beatrun.toolsmenu.gameplay.quickturnhandsonly=Quickturn Лише з Руками
beatrun.toolsmenu.gameplay.quickturnhandsonlydesc=Перемикає Quickturn лише з "Runner Hands"

beatrun.toolsmenu.gameplay.autohandswitch=Автоматичне перемикання на руки
beatrun.toolsmenu.gameplay.autohandswitchdesc=Автоматично перемикатися на "Runner Hands" під час певних рухів

beatrun.toolsmenu.gameplay.puristmode=Режим Purist
beatrun.toolsmenu.gameplay.puristmodedesc=Режим Purist це клієнтський параметр який сильно знижує рух гравця вбік перебуваючи в повітрі, прямо як в оригінальній ME.\n0 = Без обмежень\n1 = Знижує рух гравця в повітрі вбік

beatrun.toolsmenu.gameplay.disablegrapple=Вимкнути Гак-Кішку
beatrun.toolsmenu.gameplay.disablegrappledesc=Перемикає використання гака-кішки

beatrun.toolsmenu.gameplay.rollspeedloss=Втрата швидкості при перекаті
beatrun.toolsmenu.gameplay.rollspeedlossdesc=Перемикає втрату швидкості при перекаті

beatrun.toolsmenu.gameplay.wind=Ефект Вітру
beatrun.toolsmenu.gameplay.winddesc=Шум вітру під час бігу

# Tools Menu Misc Section
beatrun.toolsmenu.misc.name=Інше
beatrun.toolsmenu.misc.desc=Інші налаштування

beatrun.toolsmenu.misc.propspawn=Створення Пропів
beatrun.toolsmenu.misc.propspawndesc=Дозволяє гравцям без адмін прав створювати пропи

beatrun.toolsmenu.misc.weaponspawn=Створення Зброї
beatrun.toolsmenu.misc.weaponspawndesc=Дозволяє гравцям без адмін прав створювати зброю

beatrun.toolsmenu.misc.overdrivemp=Overdrive в Мультиплеєрі
beatrun.toolsmenu.misc.overdrivempdesc=Дозволяє використання Overdrive в мультиплеєрі

beatrun.toolsmenu.misc.healthregen=Регенерація здоров'я
beatrun.toolsmenu.misc.healthregendesc=Перемикає регенерацію здоров'я

beatrun.toolsmenu.misc.lerealisticclimbing=Реалістичний паркур
beatrun.toolsmenu.misc.lerealisticclimbingdesc=Не дає бігати по стінах і підійматися за краї, якщо не використовуються "Runner Hands"

beatrun.toolsmenu.misc.ledgegrabdamage=Урон при захопленні за кут
beatrun.toolsmenu.misc.ledgegrabdamagedesc=Перемикає урон при захопленні за кут на великій швидкості

# Tools Menu Moves Section
beatrun.toolsmenu.moves.name=Рухи
beatrun.toolsmenu.moves.desc=Налаштування рухів
beatrun.toolsmenu.moves.help=Пірнути Можна за Допомогою Ctrl + ПКМ Перебуваючи в Повітрі!\nOverdrive Перемикається за Допомогою E + ЛКМ.

beatrun.toolsmenu.moves.speedlimit=Обмеження Швидкості
beatrun.toolsmenu.moves.speedlimitdesc=Змінює обмеження швидкості пересування\nЗа замовчуванням: 325

beatrun.toolsmenu.moves.forcepuristmode=Примусовий Режим Purist
beatrun.toolsmenu.moves.forcepuristmodedesc=Вмикає режим Purist для всіх гравців

beatrun.toolsmenu.moves.realisticwallrunning="Реалістичний" Біг по Стінах
beatrun.toolsmenu.moves.realisticwallrunningdesc=Немає втрати швидкості якщо вимкнути

beatrun.toolsmenu.moves.kickglitch=Версія Kick Glitch
beatrun.toolsmenu.moves.kickglitch0=Вимкнено
beatrun.toolsmenu.moves.kickglitch1=Оригінал (множення прискорення)
beatrun.toolsmenu.moves.kickglitch2=Як в Mirror's Edge (невидима платформа)

beatrun.toolsmenu.moves.quakejump=Quake Jump
beatrun.toolsmenu.moves.quakejumpdesc=Перемикає Quake Jump\nНатисніть Стрибок одразу після Side Step

beatrun.toolsmenu.moves.sidestep=Side Step
beatrun.toolsmenu.moves.sidestepdesc=Перемикає Side Step\nA/D + ПКМ

beatrun.toolsmenu.moves.disarm=Роззброєння
beatrun.toolsmenu.moves.disarmdesc=Перемикає можливість роззброїти (вбити) NPC\nНатисніть ВИКОРИСТАТИ на NPC

beatrun.toolsmenu.moves.divesettings=Налаштування пірнання

beatrun.toolsmenu.moves.totsugeki=Totsugeki
beatrun.toolsmenu.moves.totsugekidesc=Перемикає Totsugeki\nПірнути одразу після Quake Jump

beatrun.toolsmenu.moves.totsugekispam=Спам Totsugeki
beatrun.toolsmenu.moves.totsugekispamdesc=Перемикає можливість спамити Totsugeki

beatrun.toolsmenu.moves.totsugekiheading=Кут Totsugeki
beatrun.toolsmenu.moves.totsugekiheadingdesc=Дозволяє робити Totsugeki по осі X (вгору/вниз)

beatrun.toolsmenu.moves.totsugekidirection=Напрямок Totsugeki
beatrun.toolsmenu.moves.totsugekidirectiondesc=Дозволяє робити Totsugeki в напрямку очей\nCombined with Spam and Heading Allows You to Fly =)

beatrun.toolsmenu.moves.totsugekiaudio=Звук Totsugeki
beatrun.toolsmenu.moves.totsugekiaudiodesc=Перемикає звук Totsugeki

# Tools Menu Gamemodes Section
beatrun.toolsmenu.gamemodes.name=Режими
beatrun.toolsmenu.gamemodes.desc=Налаштування режимів
beatrun.toolsmenu.gamemodes.error=Інший режим вже запущено!

beatrun.toolsmenu.gamemodes.infection=Перемкнути Infection
beatrun.toolsmenu.gamemodes.infectionstarttime=Час перед початком
beatrun.toolsmenu.gamemodes.infectiongametime=Тривалість
beatrun.toolsmenu.gamemodes.infectiontime=Час в секундах
beatrun.toolsmenu.gamemodes.datatheft=Перемкнути Data Theft
beatrun.toolsmenu.gamemodes.deathmatch=Перемкнути Deathmatch
beatrun.toolsmenu.gamemodes.eventmode=Перемкнути режим івенту
beatrun.toolsmenu.gamemodes.loadoutseditor=Редактор спорядження
beatrun.toolsmenu.gamemodes.blacklisteditor=Чорний список

# Tools Menu Extra Section
beatrun.toolsmenu.extra.name=Додатково
beatrun.toolsmenu.extra.desc=Дод. налаштування для спідранерів/потіючих хлопців

beatrun.toolsmenu.extra.stats=Дод. стати
beatrun.toolsmenu.extra.statsdesc=Показує додаткові стати біля спідометра

beatrun.toolsmenu.extra.speedrunsverif=Стати для верифікації спідранів
beatrun.toolsmenu.extra.speedrunsverifdesc=Показує ваші налаштування в кутку екрана (Purist Mode, Purist wallrun та версія Kick Glitch)

# Loadouts and Blacklist Editor
beatrun.loadoutseditor.title=Редактор спорядження
beatrun.loadoutseditor.loadout=Спорядження %s
beatrun.loadoutseditor.addweapon=Додати зброю

beatrun.blacklisteditor.title=Чорний список (для випадкового спорядження)
beatrun.blacklisteditor.blacklisted=Заборонено
beatrun.blacklisteditor.allowed=Дозволено

# Checkpoints
beatrun.checkpoints.countdown1=Раз
beatrun.checkpoints.countdown2=Два
beatrun.checkpoints.countdown3=ПОШОВ!

# DataTheft
beatrun.datatheft.name=Data Theft (%s)
beatrun.datatheft.start=Data Theft! Вбивайте гравців, збирайте кубики та вкладайте в банк щоб заробляти очки

# Deathmatch
beatrun.deathmatch.name=Deathmatch
beatrun.deathmatch.start=Deathmatch! Вбивайте гравців щоб заробляти очки

# Eventmode
beatrun.eventmode.name=[ІВЕНТ]
beatrun.eventmode.start=Івент почався! Слідуйте інструкціям від менеджера.
beatrun.eventmode.memberlabel=Учасник
beatrun.eventmode.memberhud=Ви берете участь в івенті!
beatrun.eventmode.suspendedlabel=Виключений
beatrun.eventmode.suspendedhud=Ви були виключені з івенту!
beatrun.eventmode.managerlabel=Менеджер
beatrun.eventmode.managerhud=[МЕНЕДЖЕР]

# Infection
beatrun.infection.name=Infection
beatrun.infection.infectedtext=(Заражений)
beatrun.infection.humantext=(Людина)
beatrun.infection.start=Infection! Торкайтеся інших гравців щоб заразити їх\n%s гравця(ів) буде обрано через %s сек
beatrun.infection.nosurvivors=Ніхто...
beatrun.infection.infected=був заражений!
beatrun.infection.infectedby=заразив
beatrun.infection.award=Ви отримали 200 XP за виживання!
beatrun.infection.awardinfected=Ви отримали 100 XP за спавн зараженим!
beatrun.infection.end=Гра закінчена!\nВижили: %s\nПерезапуск через 15 сек

# Server ConVars
beatrun.randomloadoutsdesc=Вибір випадкового спорядження для Deathmatch і DataTheft
beatrun.randombeatrunloadouts=Кастомне спорядження
beatrun.randommwloadouts=Спорядження з MW Base
beatrun.randomarc9loadouts=Спорядження з ARC9
beatrun.randomarccwloadouts=Спорядження з ARCCW
beatrun.randomtfaloadouts=Спорядження з TFA